/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora_tarea;

/**
 *
 * @author Abdenago
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tvalor1 = new javax.swing.JTextField();
        bcalcular = new javax.swing.JButton();
        tvalor2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rsuma = new javax.swing.JRadioButton();
        rresta = new javax.swing.JRadioButton();
        rmult = new javax.swing.JRadioButton();
        rdiv = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lresultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        tvalor1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tvalor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvalor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvalor1ActionPerformed(evt);
            }
        });
        jPanel1.add(tvalor1);
        tvalor1.setBounds(160, 50, 90, 80);

        bcalcular.setBackground(new java.awt.Color(0, 0, 0));
        bcalcular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bcalcular.setForeground(new java.awt.Color(255, 255, 255));
        bcalcular.setText("Calcular");
        bcalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcalcularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcalcularMouseExited(evt);
            }
        });
        bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalcularActionPerformed(evt);
            }
        });
        jPanel1.add(bcalcular);
        bcalcular.setBounds(210, 140, 140, 50);

        tvalor2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tvalor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvalor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvalor2ActionPerformed(evt);
            }
        });
        jPanel1.add(tvalor2);
        tvalor2.setBounds(290, 50, 90, 80);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Valor 1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 100, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Valor 2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 10, 100, 40);

        buttonGroup1.add(rsuma);
        rsuma.setText("suma");
        jPanel1.add(rsuma);
        rsuma.setBounds(410, 50, 110, 21);

        buttonGroup1.add(rresta);
        rresta.setText("resta");
        jPanel1.add(rresta);
        rresta.setBounds(410, 70, 98, 21);

        buttonGroup1.add(rmult);
        rmult.setText("multipilcacion");
        jPanel1.add(rmult);
        rmult.setBounds(410, 90, 140, 21);

        buttonGroup1.add(rdiv);
        rdiv.setText("division");
        jPanel1.add(rdiv);
        rdiv.setBounds(410, 110, 100, 21);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 160, 580, 210);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        lresultado.setBackground(new java.awt.Color(255, 0, 51));
        lresultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lresultado.setForeground(new java.awt.Color(255, 51, 102));
        lresultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lresultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lresultado);
        lresultado.setBounds(40, 20, 340, 80);
        lresultado.getAccessibleContext().setAccessibleName("lresultado");

        getContentPane().add(jPanel2);
        jPanel2.setBounds(120, 30, 440, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcalcularActionPerformed
       
        float num1= 0, num2 = 0, total = 0; 
        
        
        num1 = Float.parseFloat(tvalor1.getText());
        num2 = Float.parseFloat(tvalor2.getText());
        
        
        if (rsuma.isSelected()) {
            
             total = num1 + num2;
            
        } else if (rresta.isSelected()) {
            
            total = num1 - num2;
            
        }else if (rmult.isSelected()) {
            
             total = num1 * num2;
             
        } else if (rdiv.isSelected()) {
            
             total = num1 / num2;
        }
               
                   
       lresultado.setText(String.valueOf(total));
        
    }//GEN-LAST:event_bcalcularActionPerformed

    private void bcalcularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcalcularMouseEntered
        
        /*lresultado.setText("CALCULADORA");*/
        
    }//GEN-LAST:event_bcalcularMouseEntered

    private void bcalcularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcalcularMouseExited
        
         /*lresultado.setText(" ");*/
        
    }//GEN-LAST:event_bcalcularMouseExited

    private void tvalor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvalor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvalor2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        rsuma.setSelected(true);
        
        
    }//GEN-LAST:event_formWindowActivated

    private void tvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvalor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvalor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lresultado;
    private javax.swing.JRadioButton rdiv;
    private javax.swing.JRadioButton rmult;
    private javax.swing.JRadioButton rresta;
    private javax.swing.JRadioButton rsuma;
    private javax.swing.JTextField tvalor1;
    private javax.swing.JTextField tvalor2;
    // End of variables declaration//GEN-END:variables
}
